// <auto-generated />
/* ************************************************************
 * 
 * 
 * AUTO GENERERATED - DO NOT ALTER
 * 
 * 
 * ************************************************************/
namespace GalaxiaUniversity.TestKit.Factories
{
    using Moq;
	using GalaxiaUniversity.Web.Angular.Controllers;
	using NRepository.Core.Query;

    // Auto generated
	public partial class MainControllerFactory
	{
        private readonly MockBehavior _MockBehaviour;

		public MainControllerFactory()
            : this(MockBehavior.Default)
        {
		}

		public MainControllerFactory(MockBehavior mockBehaviour)
        {
			_MockBehaviour = mockBehaviour;

        	QueryRepositoryMock = new Mock<IQueryRepository>(_MockBehaviour);
		
			Initalise();
		}

		partial void Initalise();

		// IQueryRepository
		private IQueryRepository _IQueryRepository;
        public Mock<IQueryRepository> QueryRepositoryMock { get; set; }
        public IQueryRepository _GetQueryRepository() { return _IQueryRepository ?? QueryRepositoryMock.Object; }
	    public IQueryRepository _SetQueryRepository(IQueryRepository obj){ _IQueryRepository = obj; return obj;}

	    public MainController  Object
        {
			get { return new MainController(_GetQueryRepository()); }
		}

		public void VerifyAll()
        {
			QueryRepositoryMock.VerifyAll();
		}
	}

}
